// Import the generated lexer and parser (assumed to be generated by antlr4ts or similar)
import { CharStreams, CommonTokenStream } from "antlr4";

import MegaParser from "./grammar/MMSParse.js";
import MegaLexer from "./grammar/MMSLex.js";

// Example function to parse an expression string
export function parseExpression(input: string) {
  const chars = CharStreams.fromString(input);
  const lexer = new MegaLexer(chars);
  const tokens = new CommonTokenStream(lexer);

  const parser = new MegaParser(tokens);

  // Start parsing from the 'prog' rule as defined in Expr.antlr
  const tree = parser.file();
  return tree;
}
